# Generated by Django 4.2.25 on 2025-10-23 18:16

import biblioteca.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lector',
            name='digito_verificador',
        ),
        migrations.AlterField(
            model_name='lector',
            name='rut_lector',
            field=models.CharField(max_length=12, unique=True, validators=[biblioteca.models.validar_rut]),
        ),
    ]
