# Generated by Django 4.2.25 on 2025-10-23 19:37

import biblioteca.models
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0002_remove_lector_digito_verificador_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lector',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, default=datetime.date(1, 1, 1), validators=[biblioteca.models.validar_mayoria_edad]),
        ),
    ]
