# Generated by Django 5.2.7 on 2025-11-20 19:07

import biblioteca.models
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('biblioteca', '0003_lector_fecha_nacimiento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autor',
            name='biografia',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='autor',
            name='id_nacionalidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.nacionalidad'),
        ),
        migrations.AlterField(
            model_name='autor',
            name='pseudonimo',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='id_direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.direccion'),
        ),
        migrations.AlterField(
            model_name='biblioteca',
            name='web',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='descripcion',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='departamento',
            field=models.CharField(max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='direccion',
            name='detalles',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='lector',
            name='correo_lector',
            field=models.CharField(max_length=255, null=True, validators=[biblioteca.models.validar_correo]),
        ),
        migrations.AlterField(
            model_name='lector',
            name='fecha_nacimiento',
            field=models.DateField(default=datetime.date(1, 1, 1), null=True, validators=[biblioteca.models.validar_mayoria_edad]),
        ),
        migrations.AlterField(
            model_name='lector',
            name='id_direccion',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.direccion'),
        ),
        migrations.AlterField(
            model_name='libro',
            name='id_categoria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='biblioteca.categoria'),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_devolucion',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='prestamo',
            name='fecha_retorno',
            field=models.DateTimeField(null=True),
        ),
    ]
